Sre 867 instrumentation
bukalapak/godec pull request #13
Opened 2018-08-02 06:48 UTC by evo3cx

2018-08-06 23:54 UTC, indrasaputra requested changes

2018-08-06 23:54 UTC, indrasaputra commented on template/instrumentation.go.tmpl
> +	instrument.ObserveLatency(interfaceName, methodName, "ok", elapsedTime)
instrument ini dari mana ya?

2018-08-06 23:54 UTC, indrasaputra commented on template/instrumentation.go.tmpl
> +	instrument.ObserveLatency(interfaceName, methodName, "ok", elapsedTime)
karena ini public repo, kayaknya ga baik kalau pake private repo nya bukalapak

2018-08-06 23:54 UTC, indrasaputra commented
@evo3cx travis-ci nya masih failed euy

2018-08-07 08:29 UTC, evo3cx commented
iya invalid ini gara2 goparser unit_test saya ubah dengan testCase nya saya benar, masalah terkait goparser yang tidak tau underlying package untuk custom type

2018-08-07 08:30 UTC, evo3cx commented on template/instrumentation.go.tmpl
> +	instrument.ObserveLatency(interfaceName, methodName, "ok", elapsedTime)
owh iya yah. hmm saya tambahkan param terkait metrics saja yah

2018-08-10 04:00 UTC, indrasaputra approved these changes

2018-08-10 04:00 UTC, indrasaputra commented
@evo3cx ci nya masih fail Za. dibenerin dulu ya

2018-08-10 04:13 UTC, evo3cx commented
ini di merge dulu aja yah? go parser nya saya ganti pakai package `reflect` aja? nanti buat story baru gmn, soalnya butuh refactor

2018-08-10 04:15 UTC, evo3cx commented
sementara unit test nya saya kembalikan dulu

2018-08-10 04:17 UTC, indrasaputra commented
@evo3cx unit test nya dikembalikan dulu aja. kalo ci nya udah ijo, merge. trus nanti benerin pake reflect.

2018-08-10 04:25 UTC, evo3cx commented
saya ga bisa merge btw :cry:  

cc: @indrasaputra

2018-08-10 04:27 UTC, merged

2018-08-10 04:27 UTC, indrasaputra commented
@evo3cx merged yaa 🙏